    DROP DATABASE IF EXISTS BICICLETA;

    CREATE DATABASE BICICLETA;

    USE BICICLETA;

    CREATE TABLE USUARIO (
        EMAIL VARCHAR(100) UNIQUE NOT NULL,
        TELEFONE VARCHAR(15) NOT NULL,
        SENHA VARCHAR(20) NOT NULL,
        SEXO CHAR(1),
        CPF INT(11) UNIQUE NOT NULL,
        NASCIMENTO DATE NOT NULL,
        NOME VARCHAR(256) NOT NULL,
        PAPEL VARCHAR(10)
    );

    CREATE TABLE LOCADORA (        
        EMAIL VARCHAR(100) UNIQUE NOT NULL ,
        CNPJ VARCHAR(14) UNIQUE NOT NULL PRIMARY KEY,
        CIDADE VARCHAR(20),
        SENHA VARCHAR(20),
        NOME VARCHAR(30)
    );

    CREATE TABLE CADASTROS (
        ID BIGINT PRIMARY KEY AUTO_INCREMENT,
        DIA VARCHAR(11),
        HORA VARCHAR(5),
        CPF INT(11) NOT NULL,
        CNPJ VARCHAR(14) NOT NULL,
        FOREIGN KEY (CPF) REFERENCES USUARIO(CPF),
        FOREIGN KEY (CNPJ) REFERENCES LOCADORA(CNPJ)
    );

    INSERT INTO USUARIO (EMAIL, TELEFONE, SEXO, CPF, NASCIMENTO, NOME, PAPEL, SENHA) VALUES ('abc@123.com.bc', '19999776600', 'M', 4324123, '2001-03-12', 'Giovani', 'ADMIN', 'ADMIN');

    INSERT INTO USUARIO (EMAIL, TELEFONE, SEXO, CPF, NASCIMENTO, NOME, PAPEL, SENHA) VALUES ('def@123.com.bc', '19999556600', 'M', 1234321, '2001-03-12', 'Gabriel',  'USER', 'USER');

    INSERT INTO LOCADORA (EMAIL, CNPJ, CIDADE, SENHA, NOME) VALUES ('EMPRESA@GMAIL.COM', '12345678901234', 'PIRACICABA', 'admin', 'caterpillar');

    INSERT INTO CADASTROS (DIA, HORA, CPF, CNPJ) VALUES ('12/02/2001', '13:00', 1234321,'12345678901234' );